Repository adobe/aem-core-cif-components, pull requests merged in 2019-12, with the labels that each got.

#158 CIF-1115 - Allow product dnd on product carousel
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/MultiFieldDropTargetPostProcessor.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/MultiFieldDropTargetPostProcessorTest.java
  bundles/core/src/test/resources/context/drop-target-post-processor.json
  bundles/core/src/test/resources/simplelogger.properties
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_editConfig.xml
Labels: To Verify

#169 @trivial - add release-drafter config
  .github/release-drafter.yml
Labels: releng

#160 CIF-1120 - Make loading of countries in checkout more robust
  parent/pom.xml
  react-components/src/components/Checkout/__test__/__snapshots__/editableForm.test.js.snap
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/editableForm.js
  react-components/src/utils/__test__/hooks.test.js
  react-components/src/utils/hooks.js
Labels: Verified, bug

#165 CIF-1157 - Optimize query of FeaturedCategoryList component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-alias-result.json
Labels: Verified, enhancement

#171 Security related update of NPM dependencies
  react-components/package-lock.json
  ui.apps/package-lock.json
  ui.apps/package.json
Labels: bug
