Repository adobe/aem-core-cif-components, pull requests merged in 2020-05, with the labels that each got.

#260 @trivial - update versions after release
  README.md
  VERSIONS.md
Labels: releng

#262 CIF-1362: Pagination bar fixes
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
Labels: bug

#224 CIF-1300 - Implement mock GraphQL HTTP endpoint for the components library pages
  .circleci/codecov.yml
  .circleci/config.yml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  examples/bundle/pom.xml
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-attributes.json
  examples/bundle/src/main/resources/graphql/magento-graphql-categories.json
  examples/bundle/src/main/resources/graphql/magento-graphql-category-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-crosssellproducts.json
  examples/bundle/src/main/resources/graphql/magento-graphql-featuredcategorylist.json
  examples/bundle/src/main/resources/graphql/magento-graphql-introspection.json
  examples/bundle/src/main/resources/graphql/magento-graphql-productcarousel.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-productteaser.json
  examples/bundle/src/main/resources/graphql/magento-graphql-relatedproducts.json
  examples/bundle/src/main/resources/graphql/magento-graphql-searchresults-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-searchresults.json
  examples/bundle/src/main/resources/graphql/magento-graphql-storeconfig.json
  examples/bundle/src/main/resources/graphql/magento-graphql-upsellproducts.json
  examples/bundle/src/main/resources/graphql/magento-schema-2.3.4.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/MockGraphqlClient.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/MockUrlProviderConfiguration.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/ResourceTypeImplementationPicker.java
  examples/bundle/src/test/resources/context/jcr-content.json
  examples/bundle/src/test/resources/logback-test.xml
  pom.xml
Labels: Verified, do not merge, feature

#258 CIF-1356 - Add caching support to the GraphQL client
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/FilterAttributeMetadataCacheImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/FilterAttributeMetadataCache.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchFilterService.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/FilterAttributeMetadataCacheImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-empty-data.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  parent/pom.xml
Labels: enhancement

#264 CIF-1375 - Wrong title in design dialog of related products component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_design_dialog/.content.xml
Labels: bug

#265 CIF-890 - Create the Core CIF Components library pages - for server-side components
  .circleci/codecov.yml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  examples/README.md
  examples/bundle/pom.xml
  examples/pom.xml
  examples/ui.apps/pom.xml
  examples/ui.apps/src/main/content/META-INF/vault/filter.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/css.txt
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/js.txt
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/css.txt
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/js.txt
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.less.template
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/demo/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/demo/_cq_htmlTag/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.config
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl-examples.config
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.graphql.magento.GraphqlDataServiceImpl-examples.config
  examples/ui.content/pom.xml
  examples/ui.content/src/main/content/META-INF/vault/filter.xml
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/cloudconfigs/.content.xml
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/cloudconfigs/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  parent/pom.xml
  pom.xml
Labels: To Verify, documentation

#268 CIF-1384 - Create the Core CIF Components library pages - productteas…
  examples/bundle/src/main/resources/graphql/magento-graphql-productteaser.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/cif-demo.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/css.txt
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/productteaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productteaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/summit-watch/mg03-br-0.jpg/_jcr_content/renditions/original.dir/.content.xml
Labels: Verified, documentation

#271 CIF-1385 - Create the Core CIF Components library pages - productcarousel component
  examples/bundle/src/main/resources/graphql/magento-graphql-productcarousel.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/resources/context/jcr-content.json
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/cif-demo.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/productcarousel/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productcarousel/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/fusion-backpack/mb02-gray-0.jpg/_jcr_content/renditions/original.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-orange_main_2.jpg/_jcr_content/renditions/original.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-red_main_2.jpg/_jcr_content/renditions/original.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/ingrid-running-jacket/wj04-white_main_2.jpg/_jcr_content/renditions/original.dir/.content.xml
Labels: Verified, documentation

#273 CIF-1394 - Product asset drag'n'drop on a page should configure produ…
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_editConfig.xml
Labels: To Verify, bug

#276 CIF-1383 - Create the Core CIF Components library pages - productlist…
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-category-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-category.json
  examples/bundle/src/main/resources/graphql/magento-graphql-introspection.json
  examples/bundle/src/main/resources/graphql/magento-luma-schema-2.3.5.json
  examples/bundle/src/main/resources/graphql/magento-schema-2.3.4.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/productlist/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/productlist/_cq_htmlTag/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/bruno-compete-hoodie/mh03-black_main_2.jpg/_jcr_content/renditions/original.dir/.content.xml
Labels: To Verify, documentation

#277 CIF-1403 - CIF components library - Add example for Grouped Product
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-grouped-product.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/yoga-strap/luma-yoga-strap-set.jpg/_jcr_content/renditions/original.dir/.content.xml
Labels: To Verify, documentation

#279 CIF-1387 - Create the Core CIF Components library pages - search comp…
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-products-collection.json
  examples/bundle/src/main/resources/graphql/magento-graphql-searchresults-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-searchresults.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/cif-demo.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/searchbar/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/searchresults/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/searchresults/_cq_htmlTag/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/search/.content.xml
Labels: To Verify, documentation

#270 [React Components] update setShippingAddressOnCart to refetch cart details
  react-components/src/components/Checkout/editableForm.js
Labels: To Verify, bug
