Repository adobe/aem-core-cif-components, pull requests merged in 2020-07, with the labels that each got.

#320 CIF-1472 - Support Bundle Products: price display
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-bundleproduct-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  ui.apps/karma.conf.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/PriceFormatter.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/clientlibs/js/productcollection.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commons/v1/price.html
  ui.apps/test/components/commerce/product/groupedProductTest.js
  ui.apps/test/components/commerce/product/productTest.js
  ui.apps/test/components/commerce/productcollection/productCollectionTest.js
Labels: Verified, feature

#324 CIF-1478 - Venia css for components library is not up-to-date
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
Labels: Verified, bug

#322 CIF-1228 - Update Product Media Query in Components because of Deprecation in Magento 2.3.5
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/main/resources/product-component-placeholder-data.json
  bundles/core/src/main/resources/productlist-component-placeholder-data.json
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-groupedproduct-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productteaser-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-virtualproduct-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-grouped-product.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-storeconfig.json
  parent/pom.xml
Labels: Verified, enhancement

#305 CIF-1369: Support for Preview with Product in page editor
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServletTest.java
Labels: enhancement

#330 CIF-1484 - Panel title not updated when returning to sign-in
  react-components/src/actions/navigation/actions.js
  react-components/src/context/NavigationContext.js
Labels: Verified, bug

#329 CIF-1492 - [Github] Issue #317
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
Labels: To Verify, bug

#332 CIF-1480 - Move the `react-components` project from the Core Components to the Venia Project
  ui.apps/pom.xml
  ui.apps/src/main/javascript/react-components/.eslintrc.js
  ui.apps/src/main/javascript/react-components/package-lock.json
  ui.apps/src/main/javascript/react-components/package.json
  ui.apps/src/main/javascript/react-components/src/README.md
  ui.apps/src/main/javascript/react-components/src/i18n.js
  ui.apps/src/main/javascript/react-components/src/index.js
  ui.apps/src/main/javascript/react-components/webpack.config.js
Labels: Verified, enhancement

#334 CIF-1470 - Ban usage of AEM Commerce Classic API for CIF Core Components
  bundles/core/macker-rules.xml
  bundles/core/pom.xml
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
Labels: bug

#335 CIF-1416 - Add CIF Core Components to AEM Components Library Page
  examples/README.md
  examples/bundle/pom.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.config
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl-examples.config
Labels: To Verify, bug

#336 CIF-1509 - The productlist component should not return any product wh…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
Labels: To Verify, bug

#337 CIF-1510 - The searchresults component should not perform any GraphQL…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: Verified, bug

#331 CIF-1485 - The cq:catalogPath restriction not applied to picker when previewing non-empty page
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServletTest.java
Labels: bug

#338 CIF-1511 - CIF components library text about "placeholders" should be…
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
Labels: documentation

#339 CIF-1514 - Rendering of pages using CIF component is failing
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactory.java
Labels: Verified, bug

#341 CIF-1516 Use a short-lived resolver in ComponentsConfigurationAdapterFactory
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/ComponentsConfiguration.java
Labels: To Verify, bug

#345 CIF-1497 - Setup IT infrastructure for CIF components
  .circleci/ci/build.js
  .circleci/ci/ci.js
  .circleci/ci/it-tests.js
  .circleci/config.yml
Labels: testing

#342 CIF-1496 - Embed cif.shell.picker clientlib via dialogs
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
Labels: Verified

#323 CIF-1240 - Braintree validation error clear
  react-components/src/components/Checkout/paymentsForm.js
Labels: bug

#350 CIF-1522 - Simplify the @adobe/aem-core-cif-react-components package
  react-components/package.json
Labels: Verified

#347 CIF-1498 - Setup IT project for CIF components
  .circleci/ci/it-tests.js
  .circleci/config.yml
  examples/ui.apps/pom.xml
  examples/ui.content/pom.xml
  it/http/README.md
  it/http/pom.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceTeaserComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceTestBase.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/FeaturedCategoryListComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/GraphqlOSGiConfig.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/NavigationComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductCarouselComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductTeaserComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/RelatedProductsComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/SearchResultsComponentIT.java
  parent/pom.xml
  pom.xml
Labels: testing

#351 CIF-1533 - [React components] The "add to cart" mutation uses a string instead of a float
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/components/Minicart/useMinicart.js
  react-components/src/queries/mutation_add_to_cart.graphql
Labels: bug
