Repository adobe/aem-core-cif-components, pull requests merged in 2020-06, with the labels that each got.

#290 CIF-1390 - Create the Core CIF Components library pages - featuredcat…
  examples/bundle/src/main/resources/graphql/magento-graphql-featuredcategorylist.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/resources/context/jcr-content.json
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/featuredcategorylist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/featuredcategorylist/.content.xml
Labels: To Verify, documentation

#289 CIF-1389 - Create the Core CIF Components library pages - teaser comp…
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/image/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/image/_cq_editConfig.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/teaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/teaser/.content.xml
Labels: To Verify, documentation

#292 CIF-1392 - CIF Components library pages - Add support for client-side…
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/search/.content.xml
Labels: To Verify, documentation

#294 CIF-1425 - The code handling search filters should be covered by unit…
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: releng

#299 @trivial - fix dispatcher template
  dispatcher/conf/dispatcher.any
  dispatcher/conf/magento-proxy.conf
Labels: releng

#298 Combine category query with product search query
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchResultsService.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: Verified, enhancement

#301 CIF-1364: Show count in productcollection template
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
Labels: To Verify, enhancement

#297 CIF-1416 - Add CIF Core Components to AEM Components Library Page
  .circleci/config.yml
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchFilterService.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchResultsService.java
  examples/README.md
  examples/ui.apps/pom.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.config
  examples/ui.content/pom.xml
  parent/pom.xml
  ui.apps/pom.xml
Labels: Verified, bug

#304 CIF-1358: Allow category filtering for searches
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
Labels: enhancement

#284 Editing shipping address / shipping method doesn't update cart
  react-components/src/components/Checkout/editableForm.js
Labels: Verified, bug

#307 @releng - align the versions of all the modules to the next snapshot …
  README.md
  all/pom.xml
  bundles/core/pom.xml
  examples/bundle/pom.xml
  examples/pom.xml
  examples/ui.apps/pom.xml
  examples/ui.content/pom.xml
  parent/pom.xml
  pom.xml
  react-components/pom.xml
  ui.apps/pom.xml
Labels: releng

#308 Bug fix for github issue #286
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: Verified, bug

#296 CIF-1365 - Support product sorting
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SorterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SorterKeyImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchOptions.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchResultsSet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/Sorter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SorterKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  parent/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/clientlibs/js/productcollection.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/sorting.html
Labels: feature

#306 Revert "CIF-1394 - Product asset drag'n'drop on a page should configu…
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_editConfig.xml
Labels: To Verify, bug

#282 CIF-1415 - [Cart] Editing the quantity doesn't update the cart
  react-components/src/actions/cart/__test__/actions.test.js
  react-components/src/actions/cart/actions.js
  react-components/src/components/Minicart/cartInitializer.js
  react-components/src/components/Minicart/cartOptions.js
  react-components/src/components/Minicart/useCartOptions.js
  react-components/src/components/SignIn/useSignin.js
Labels: To Verify, bug

#309 CIF-1464 - The FeaturedCategoryList component does not use the UrlPro…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
Labels: Verified, bug

#300 CIF-1447 - The Core CIF Components must use a service user to access configurations
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/ComponentsConfiguration.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactoryTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  bundles/core/src/test/resources/context/jcr-conf.json
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  parent/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-graphqlclient.xml
Labels: Verified

#311 Remove default configuration of i18next-browser-languagedetector
  ui.apps/src/main/javascript/react-components/src/i18n.js
Labels: bug

#314 CIF-1436 - Can't remove or edit items from shopping cart
  react-components/src/components/Minicart/__test__/couponForm.test.js
  react-components/src/components/Minicart/__test__/couponItem.test.js
  react-components/src/components/Minicart/__test__/product.test.js
  react-components/src/components/Minicart/__test__/useCouponForm.test.js
  react-components/src/components/Minicart/__test__/useCouponItem.test.js
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/cartInitializer.js
  react-components/src/components/Minicart/couponForm.js
  react-components/src/components/Minicart/couponItem.js
  react-components/src/components/Minicart/product.js
  react-components/src/components/Minicart/useCouponForm.js
  react-components/src/components/Minicart/useCouponItem.js
  react-components/src/components/Minicart/useProduct.js
Labels: Verified, bug

#312 Load Venia loading indicator (logo.svg) via CSS
  react-components/src/components/LoadingIndicator/indicator.js
Labels: Verified, bug

#315 CIF-1156 - Live copy catalog does not show if node name is not language code
  parent/pom.xml
Labels: Verified, bug

#316 releng - Update release version in README
  README.md
  VERSIONS.md
Labels: releng

#318 CIF-1471 - Use the ValueMapDecorator from the Sling API instead of the one from the Commerce API
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/ComponentsConfiguration.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  examples/bundle/pom.xml
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
Labels: bug

#310 CIF-1437: Content Teaser CTA bug fix
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  ui.apps/karma.conf.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/css/teaser.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/js.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/js/teaser.js
  ui.apps/test/clientlibs/common/jQueryMockForTest.js
  ui.apps/test/components/content/teaser/teaserConfigTest.js
  ui.apps/webpack.config.js
Labels: Verified, bug
