Repository adobe/aem-core-cif-components, pull requests merged in 2020-01, with the labels that each got.

#163 CIF-1164 - Improve responsiveness of product carousel component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/product-carousel.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
Labels: To Verify, enhancement

#164 CIF-1153 - Generic related product component
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelationTypesDataSourceServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelationTypesDataSourceServletTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-crosssellproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-upsellproducts-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
Labels: Verified, feature

#167 CIF-1175 - Call-to-action button for product teaser
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/test/components/commerce/productteaser/actionsTest.js
  ui.apps/webpack.config.js
Labels: To Verify, feature

#162 CIF-1148 - i18n support for AEM server-side Core Components
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/footer.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigationHeader.html
Labels: Verified, enhancement

#170 CIF-1183 - Add change password functionality to my account section
  parent/pom.xml
  react-components/README.md
  react-components/src/components/AuthBar/container.js
  react-components/src/components/AuthModal/authModal.js
  react-components/src/components/ChangePassword/__tests_/__snapshots__/changePassword.test.js.snap
  react-components/src/components/ChangePassword/__tests_/changePassword.test.js
  react-components/src/components/ChangePassword/changePassword.css
  react-components/src/components/ChangePassword/changePassword.js
  react-components/src/components/ChangePassword/index.js
  react-components/src/components/MyAccount/myAccount.js
  react-components/src/context/UserContext.js
  react-components/src/queries/mutation_change_password.graphql
Labels: To Verify, feature

#175 CIF-1186 - Minicart error message doesn't go away unless you refresh the page
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/error.css
  react-components/src/components/Minicart/error.js
Labels: To Verify, bug

#172 Add prettier code styling to react components project
  react-components/.prettierrc
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/App/app.js
  react-components/src/components/App/index.js
  react-components/src/components/ChangePassword/__tests_/changePassword.test.js
  react-components/src/components/ChangePassword/changePassword.js
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/checkoutContext.js
  react-components/src/components/Checkout/index.js
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/error.js
  react-components/src/components/Minicart/index.js
  react-components/src/context/UserContext.js
  react-components/src/index.js
  react-components/src/utils/__test__/hooks.test.js
Labels: releng

#177 CIF-1152 - Add option to select images in 'Featured Category list' component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-alias-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/editor/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/editor/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/editor/css/dialog.less
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
Labels: To Verify

#180 CIF-1151 - Add option to hide title and category banner in 'Product list' component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_dialog/.content.xml
Labels: To Verify, enhancement

#178 CIF-1189 - Misc issues with "related products" component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/product-carousel.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
Labels: Verified, bug

#179 CIF-1045 - [Research] Edit custom PDP / PLP page
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactoryTest.java
  bundles/core/src/test/resources/context/jcr-content.json
Labels: Verified, enhancement

#182 CIF-1169 - [React Components] Use maven-frontend-plugin for building the project
  .gitignore
  parent/pom.xml
  pom.xml
  react-components/build-scripts/update-version.js
  react-components/pom.xml
  ui.apps/pom.xml
Labels: Verified, bug

#181 CIF-1205 - Clean up old cart JS leftovers
  dispatcher/README.md
  dispatcher/conf/magento-proxy.conf
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceApi.js
Labels: Verified, bug

#174 Add maven profile "autoInstallAll"
  README.md
  all/pom.xml
Labels: Verified, enhancement

#185 CIF-1225 - minor fix to not render HTML comments
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
Labels: Verified, bug

#183 CIF-1168 - [Build] Use the production build of React Components upon …
  .circleci/config.yml
  parent/pom.xml
  react-components/package.json
  react-components/pom.xml
  react-components/webpack.config.js
  ui.apps/package.json
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/react-components/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/clientlibs/.content.xml
  ui.apps/src/main/javascript/react-components/package.json
  ui.apps/src/main/javascript/react-components/webpack.config.js
Labels: Verified, releng

#187 @releng - Update dependencies before release
  bundles/core/pom.xml
  parent/pom.xml
  ui.apps/pom.xml
Labels: Verified, releng

#191 @trivial - fix component link
  README.md
Labels: documentation
