Repository adobe/aem-core-cif-components, pull requests merged in 2020-08, with the labels that each got.

#352 CIF-1529 - Include CIF Add-On in IT setup for Cloud SDK
  .circleci/ci/it-tests.js
  .circleci/config.yml
Labels: testing

#354 CIF-1547 - [React Components] Fix CSS reusability
  react-components/webpack.config.js
Labels: Verified

#359 CIF-1547 - [React Components] Fix CSS reusability
  react-components/webpack.config.js
Labels: Verified

#355 CIF-1549 - Catalog option 'Show landing page' / commerce tab does not show up under page properties
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServletTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CatalogPagePropertiesIT.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
Labels: Verified, bug

#363 @trivial - add AEM Cloud support to readme
  README.md
Labels: documentation

#365 CIF-1566 - Integration tests should not be released
  .circleci/config.yml
  pom.xml
Labels: Verified, bug

#364 CIF-1537 - split product teaser template into sub-templates
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/title.html
Labels: To Verify, enhancement

#368 CIF-1539 - Extract title, description, sku into separate templates
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/description.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/sku.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/title.html
Labels: To Verify, enhancement

#367 CIF-1536 - Product teaser: Add CTA label configuration
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
Labels: Verified, enhancement

#366 CIF-1567 - Client-side GraphQL should be validated against Magento schema
  react-components/.eslintrc.js
  react-components/src/queries/__test__/magento-schema-2.3.4.json
  react-components/src/queries/__test__/magento-schema-2.3.5.json
  react-components/src/queries/__test__/validateQueries.test.js
  ui.apps/package-lock.json
  ui.apps/package.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
  ui.apps/test/clientlibs/common/magento-schema-2.3.4.json
  ui.apps/test/clientlibs/common/magento-schema-2.3.5.json
Labels: testing

#371 CIF-1535 - Support placeholder text in searchbar component
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/search/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/searchbar.html
Labels: Verified, enhancement

#373 CIF-1416 - Add CIF Core Components to AEM Components Library Page
  all/pom.xml
  examples/README.md
  examples/all/pom.xml
  examples/pom.xml
  examples/ui.apps/pom.xml
  examples/ui.content/pom.xml
  parent/pom.xml
  ui.apps/pom.xml
Labels: Verified, releng

#361 JS warnings in the console while using the My Account dropdown
  react-components/i18n/en/account.json
  react-components/src/components/AccountContainer/__test__/__snapshots__/accountContainer.test.js.snap
  react-components/src/components/AccountContainer/__test__/__snapshots__/accountDropdown.test.js.snap
  react-components/src/components/AccountContainer/__test__/accountDropdown.test.js
  react-components/src/components/AccountContainer/accountDropdown.css
  react-components/src/components/AccountContainer/accountDropdown.js
  react-components/src/components/AddressBook/__test__/useAddressForm.test.js
  react-components/src/components/CreateAccount/createAccount.js
  react-components/src/components/CreateAccount/createAccountSuccess.js
  react-components/src/components/MyAccount/__test__/__snapshots__/myAccount.test.js.snap
  react-components/src/components/MyAccount/__test__/myAccount.test.js
  react-components/src/components/MyAccount/myAccount.js
  react-components/src/components/SignIn/__test__/signIn.test.js
  react-components/src/components/SignIn/signIn.js
  react-components/src/components/SignIn/useSignin.js
  react-components/src/context/UserContext.js
  react-components/src/context/__test__/UserContext.test.js
Labels: Verified, bug

#382 CIF-1540 - CIF breadcrumb component
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/NavigationItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/breadcrumb/Breadcrumb.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/MockUrlProviderConfiguration.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-breadcrumb-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-breadcrumb-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-not-found-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/breadcrumb/v1/breadcrumb/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/breadcrumb/v1/breadcrumb/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/breadcrumb/v1/breadcrumb/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/breadcrumb/v1/breadcrumb/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/README.md
Labels: To Verify, feature

#380 CIF-1548 - Generate CSS API file
  react-components/css-template.js
  react-components/package.json
Labels: To Verify, enhancement

#384 CIF-1590 - Remove Venia specific font from page component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
Labels: bug
