Repository adobe/aem-core-cif-components, pull requests merged in 2020-11, with the labels that each got.

#426 CIF-1654 - CIF React Core Components should support GraphQL GET requests
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/MockGraphqlClient.java
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/page.html
  it/http/src/test/java/com/adobe/cq/commerce/it/http/StoreConfigExporterIT.java
  parent/pom.xml
  react-components/src/components/App/app.js
  react-components/src/context/ConfigContext.js
  react-components/src/context/__test__/ConfigContext.test.js
  react-components/src/context/__test__/__snapshots__/ConfigContext.test.js.snap
  react-components/src/index.js
  react-components/src/utils/__test__/compressQueryFetch.test.js
  react-components/src/utils/compressQueryFetch.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html
  ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
Labels: Verified, enhancement

#259 CIF-1250 - Allow country selection during checkout
  react-components/i18n/en/checkout.json
  react-components/src/components/AddressBook/__test__/__snapshots__/addressFormContainer.test.js.snap
  react-components/src/components/AddressBook/__test__/addressFormContainer.test.js
  react-components/src/components/AddressForm/__test__/__snapshots__/addressForm.test.js.snap
  react-components/src/components/AddressForm/__test__/addressForm.test.js
  react-components/src/components/AddressForm/addressForm.js
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/__test__/useOverview.test.js
  react-components/src/components/Checkout/editableForm.js
  react-components/src/queries/query_countries.graphql
  react-components/src/utils/__test__/formValidators.test.js
  react-components/src/utils/__test__/hooks.test.js
  react-components/src/utils/formValidators.js
  react-components/src/utils/mocks/queryCountries.js
Labels: Blocked

#431 CIF-1655 - Setup automatic deployment of CIF components library to Sk…
  .github/workflows/maven-deploy-to-library.yml
Labels: releng

#432 CIF-1710 - Add category carousel illustration to CIF components examples library
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-components/categorycarousel.svg/_jcr_content/renditions/original.dir/.content.xml
Labels: Verified

#429 CIF-1037 - Template inheritance for categories
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactoryTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageServletTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/logback-test.xml
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
Labels: Blocked, Verified, feature

#430 CIF-1672 - [CIF components library] ui.frontend should use npm link
  examples/ui.frontend/.babelrc
  examples/ui.frontend/.eslintrc.js
  examples/ui.frontend/README.md
  examples/ui.frontend/package-lock.json
  examples/ui.frontend/package.json
  examples/ui.frontend/pom.xml
  examples/ui.frontend/src/main/site/app/App.js
  examples/ui.frontend/src/main/site/app/config.js
  examples/ui.frontend/src/main/site/app/i18n.js
  examples/ui.frontend/src/main/site/index.js
  examples/ui.frontend/src/main/webpack/site/main.ts
  examples/ui.frontend/tsconfig.json
  examples/ui.frontend/webpack.common.js
  examples/ui.frontend/webpack.dev.js
  examples/ui.frontend/webpack.prod.js
Labels: Verified, bug

#441 CIF-1729 - CIF Components bundle is released without sources and java…
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/navigation/Navigation.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/navigation/NavigationItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/navigation/NavigationModel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Variant.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/ComponentsConfiguration.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchOptions.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchResultsSet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/Sorter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SorterKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchFilterService.java
Labels: bug

#438 CIF-1637 - Support CIF Core Components staged catalog data with Timewarp
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/resources/context/jcr-content.json
Labels: Verified, enhancement

#439 CIF-1699 - [React Components] Clean-up the dependencies of the NPM module
  react-components/babel.config.js
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/Checkbox/checkbox.js
  react-components/src/components/Field/field.js
  react-components/src/components/Select/select.js
Labels: To Verify

#437 CIF-1711 - [React Components] Shipping Address form bugs
  react-components/src/components/AccountDetails/__test__/accountDetails.test.js
  react-components/src/components/AddressBook/__test__/__snapshots__/addressFormContainer.test.js.snap
  react-components/src/components/AddressBook/addressFormContainer.js
  react-components/src/components/AddressForm/__test__/__snapshots__/addressForm.test.js.snap
  react-components/src/components/AddressForm/__test__/useAddressSelect.test.js
  react-components/src/components/AddressForm/addressForm.js
  react-components/src/components/AddressForm/useAddressForm.js
  react-components/src/components/AddressForm/useAddressSelect.js
  react-components/src/components/Checkout/editableForm.js
  react-components/src/utils/test-utils.js
Labels: To Verify, bug

#428 CIF-1678 - Commerce Teaser should align HTL files with WCM core component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/teaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/css/teaser.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/editor/js/teaser.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/teaser.html
  ui.apps/test/clientlibs/common/jQueryMockForTest.js
  ui.apps/test/components/content/teaser/teaserConfigTest.js
Labels: enhancement

#448 CIF-1501 - XF based page footer with authoring support
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/_cq_editConfig.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/footer.html
Labels: bug
