Repository adobe/aem-core-cif-components, pull requests merged in 2020-02, with the labels that each got.

#186 CIF-1226 - Update Product Filters in Components for Magento 2.3.4 Schema
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetriever.java
  parent/pom.xml
Labels: Verified, bug

#195 CIF-1197 - Update pricing information on product list component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/VariantImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/Price.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Variant.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java
  bundles/core/src/main/resources/productlist-component-placeholder-data.json
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-crosssellproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-upsellproducts-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/price.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/js/productlist.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commons/v1/price.html
  ui.apps/test/components/commerce/product/productTest.js
  ui.apps/test/components/commerce/productlist/productListTest.js
Labels: To Verify, enhancement

#193 CIF-1233 - fix exception log message for not configured component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
Labels: To Verify, bug

#199 CIF-1188 - Use default implementations in Sling models consistently
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java
Labels: enhancement

#201 CIF-1224 - Pagination in productlist component cannot handle large product sets
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
Labels: enhancement

#202 CIF-1253 - Product Carousel does not show configurable product and pr…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
Labels: To Verify, bug

#197 CIF-1242 - adapt to Magento categories now returning full URL
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-alias-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
Labels: To Verify, bug

#203 CIF-1251 - Add advanced pricing information to product teaser
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-productteaser-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
Labels: To Verify, enhancement

#204 CIF-1229 - Release fails after npm publish
  parent/pom.xml
  react-components/package.json
  react-components/pom.xml
  ui.apps/pom.xml
Labels: To Verify, releng

#205 CIF-1282 - Navigation header is broken for empty navigation
  ui.apps/package-lock.json
  ui.apps/package.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/clientlibs/js/navigation.js
  ui.apps/test/components/commerce/navigation/navigationTest.js
Labels: bug

#206 CIF-1284 - [CIF Components] Collect all GraphQL queries generated by unit test
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-alias-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-crosssellproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-navigation-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productteaser-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-singlecategory-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-upsellproducts-result.json
  bundles/core/src/test/resources/logback-test.xml
  bundles/core/src/test/resources/simplelogger.properties
  bundles/core/src/test/resources/test-queries/README.md
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  parent/pom.xml
Labels: To Verify, releng

#208 CIF-1290 - Multi-template doesn't work for top category
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
Labels: bug

#209 CIF-1291 - The price_range query only supports configurable and simpl…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: To Verify, bug

#212 CIF-1295 - Same as CIF-1291 but for client-side price queries
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
Labels: To Verify, bug

#211 CIF-1239 - Entering shipping address does not always work
  react-components/src/components/Checkout/__test__/__snapshots__/addressForm.test.js.snap
  react-components/src/components/Checkout/__test__/addressForm.test.js
  react-components/src/components/Checkout/addressForm.js
Labels: To Verify, bug

#210 CIF-1292 - Exceptions when reading products data should not break the…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
  bundles/core/src/test/resources/logback-test.xml
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: To Verify, bug

#217 @trivial - update CIF Connector dependency
  parent/pom.xml
Labels: releng

#216 CIF-1301 - Product carousel displays exception if GraphQL client not found
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplEmptyTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/product-carousel.js
Labels: bug

#218 @releng - update readme
  README.md
  VERSIONS.md
Labels: releng
