Repository adobe/aem-core-cif-components, pull requests merged in 2020-09, with the labels that each got.

#389 CIF-1610 - Cookies are not correctly set when hostname has a port
  react-components/src/utils/hooks.js
Labels: To Verify, bug

#385 CIF-1587 - Add reverse proxy to documentation
  README.md
  dispatcher/README.md
  react-components/README.md
Labels: To Verify, documentation

#390 Fix filevault-package-maven-plugin error's
  examples/all/pom.xml
  examples/ui.apps/pom.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/image/.content.xml
  examples/ui.content/pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/_cq_dialog/.content.xml
Labels: To Verify, bug

#378 CIF-1473: Support Bundle Products: option selection
  react-components/.eslintrc.js
  react-components/i18n/en/product.json
  react-components/i18next-scanner.config.js
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/bundleProductOptions.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/checkbox.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/multiSelect.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/radio.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/select.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/bundleProductOptions.test.js
  react-components/src/components/BundleProductOptions/__test__/checkbox.test.js
  react-components/src/components/BundleProductOptions/__test__/graphQlMockReponse.js
  react-components/src/components/BundleProductOptions/__test__/multiSelect.test.js
  react-components/src/components/BundleProductOptions/__test__/radio.test.js
  react-components/src/components/BundleProductOptions/__test__/select.test.js
  react-components/src/components/BundleProductOptions/bundleProductOptions.js
  react-components/src/components/BundleProductOptions/checkbox.js
  react-components/src/components/BundleProductOptions/index.js
  react-components/src/components/BundleProductOptions/multiSelect.js
  react-components/src/components/BundleProductOptions/radio.js
  react-components/src/components/BundleProductOptions/select.js
  react-components/src/context/ConfigContext.js
  react-components/src/index.js
  react-components/src/queries/query_bundle_product.graphql
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
Labels: feature

#379 CIF-1551 - [React Components] Refactor the NavigationContext
  react-components/src/actions/navigation/index.js
  react-components/src/components/App/app.js
  react-components/src/components/AuthBar/__test__/useNavigationState.test.js
  react-components/src/components/AuthBar/authBar.js
  react-components/src/components/AuthBar/container.js
  react-components/src/components/AuthBar/myAccountPanel.css
  react-components/src/components/AuthBar/myAccountPanel.js
  react-components/src/components/AuthBar/useNavigationState.js
  react-components/src/components/AuthModal/index.js
  react-components/src/components/CreateAccount/__test__/createAccount.test.js
  react-components/src/components/Minicart/__test__/cartContext.test.js
  react-components/src/components/Minicart/__test__/minicart.test.js
  react-components/src/components/Minicart/__test__/useCouponItem.test.js
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/components/Portal/Portal.js
  react-components/src/context/ConfigContext.js
  react-components/src/context/__test__/NavigationContext.test.js
  react-components/src/queries/__test__/validateQueries.test.js
Labels: To Verify, enhancement

#396 CIF-1624: Remove commons-text dependency in UrlProviderImpl
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  examples/bundle/pom.xml
  parent/pom.xml
  ui.apps/pom.xml
Labels: To Verify

#398 releng - Fix invalid codecov.yml configuration
  .github/codecov.yml
Labels: releng

#401 Cancel button doesn't work for Forgot Password in navigation panel
  react-components/src/components/AuthBar/myAccountPanel.js
  react-components/src/components/ForgotPassword/forgotPassword.js
Labels: bug

#399 CIF-1469 - CIF Core Components support for staged catalog data
  .github/codecov.yml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MockLaunch.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/utils/SiteNavigationTest.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: Verified, feature

#391 CIF-1474 - Support Bundle Products: add-to-cart and cart display
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  react-components/README.md
  react-components/fragmentTypes.json
  react-components/src/actions/cart/__test__/actions.test.js
  react-components/src/actions/cart/actions.js
  react-components/src/components/App/app.js
  react-components/src/components/BundleProductOptions/__test__/bundleProductOptions.test.js
  react-components/src/components/BundleProductOptions/__test__/checkbox.test.js
  react-components/src/components/BundleProductOptions/__test__/multiSelect.test.js
  react-components/src/components/BundleProductOptions/__test__/radio.test.js
  react-components/src/components/BundleProductOptions/__test__/select.test.js
  react-components/src/components/BundleProductOptions/bundleProductOptions.js
  react-components/src/components/BundleProductOptions/checkbox.js
  react-components/src/components/BundleProductOptions/multiSelect.js
  react-components/src/components/BundleProductOptions/radio.js
  react-components/src/components/BundleProductOptions/select.js
  react-components/src/components/Minicart/__test__/__snapshots__/product.test.js.snap
  react-components/src/components/Minicart/minicart.js
  react-components/src/components/Minicart/product.css
  react-components/src/components/Minicart/product.js
  react-components/src/components/Minicart/useMinicart.js
  react-components/src/queries/mutation_add_bundle_to_cart.graphql
  react-components/src/queries/query_cart_details.graphql
Labels: Verified, feature

#402 CIF-1640 - Productcollection clientlib is not included in Venia demo
  bundles/core/src/main/resources/productlist-component-placeholder-data.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/images/catalog/category/category-image.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/images/catalog/category/product-thumbnail.png
Labels: Verified, bug

#403 CIF-1644 - GraphQL requests for staged data should use POST
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
Labels: Verified, bug

#405 CIF-1084 - Implement the password reset page
  react-components/i18n/en/account.json
  react-components/package-lock.json
  react-components/src/components/ForgotPassword/forgotPasswordForm.js
  react-components/src/components/ResetPassword/ResetPassword.css
  react-components/src/components/ResetPassword/ResetPassword.js
  react-components/src/components/ResetPassword/__test__/ResetPassword.test.js
  react-components/src/components/ResetPassword/__test__/__snapshots__/ResetPassword.test.js.snap
  react-components/src/components/ResetPassword/index.js
  react-components/src/components/ResetPassword/useResetPassword.js
  react-components/src/index.js
  react-components/src/queries/mutation_reset_password.graphql
  react-components/src/utils/__test__/hooks.test.js
  react-components/src/utils/hooks.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/resetpassword/v1/resetpassword/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/resetpassword/v1/resetpassword/resetpassword.html
Labels: feature

#407 CIF-1638 - Add client-side support for staged catalog data
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  bundles/core/src/test/resources/context/jcr-content.json
Labels: Verified, enhancement
