Repository adobe/aem-core-cif-components, pull requests merged in 2020-10, with the labels that each got.

#412 CIF-1653 - TTL-based caching is skipped by the SpecificPageFilterFactory
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
Labels: Verified, bug

#410 CIF-1630 - Configurable header tag for teaser and carousel components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/TitleTypeProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplEmptyTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/authoring/dialog/titletypetab/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/authoring/dialog/titletypetab/titletypes/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
Labels: Verified, enhancement

#414 CIF-1650 - "Sign In" popup on desktop view does not close
  react-components/src/components/AccountContainer/__test__/__snapshots__/accountContainer.test.js.snap
  react-components/src/components/AccountContainer/__test__/__snapshots__/accountDropdown.test.js.snap
  react-components/src/components/AccountContainer/accountDropdown.css
  react-components/src/components/AccountContainer/accountDropdown.js
  react-components/src/components/Mask/mask.js
  react-components/src/components/Minicart/minicart.js
Labels: Verified, bug

#413 CIF-1615 - CIF Addressbook component needs a readme
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/addressbook/v1/addressbook/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/README.md
Labels: bug

#418 CIF-1635: Remove @magento/peregrine dependency
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/Checkbox/__tests__/__snapshots__/checkbox.test.js.snap
  react-components/src/components/Checkbox/__tests__/checkbox.test.js
  react-components/src/components/Checkout/overview.js
  react-components/src/components/Minicart/productList.js
Labels: releng

#420 CIF-1477 - Support Bundle Products: add example in CIF components library
  examples/README.md
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-bundle-product-items.json
  examples/bundle/src/main/resources/graphql/magento-graphql-bundle-product.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/pom.xml
  examples/ui.apps/.gitignore
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/cif-demo.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/_jcr_content/folderThumbnail
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/_jcr_content/folderThumbnail.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.140.100.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.thumbnail.48.48.png.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.dir/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/original
  examples/ui.content/src/main/content/jcr_root/content/dam/core-components-examples/library/cif-sample-assets/catalog/product/sprite-yoga-companion-kit/luma-yoga-kit-2.jpg/_jcr_content/renditions/original.dir/.content.xml
  examples/ui.frontend/.babelrc
  examples/ui.frontend/.eslintignore
  examples/ui.frontend/.eslintrc.js
  examples/ui.frontend/README.md
  examples/ui.frontend/assembly.xml
  examples/ui.frontend/clientlib.config.js
  examples/ui.frontend/package-lock.json
  examples/ui.frontend/package.json
  examples/ui.frontend/pom.xml
  examples/ui.frontend/src/main/webpack/site/app/App.js
  examples/ui.frontend/src/main/webpack/site/app/config.js
  examples/ui.frontend/src/main/webpack/site/app/i18n.js
  examples/ui.frontend/src/main/webpack/site/main.ts
  examples/ui.frontend/tsconfig.json
  examples/ui.frontend/webpack.common.js
  examples/ui.frontend/webpack.dev.js
  examples/ui.frontend/webpack.prod.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/clientlibs/js/searchbar.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/clientlibs/js/navigation.js
Labels: Verified, documentation

#423 CIF-1680 - Add htl-maven-plugin to CIF ui.apps
  ui.apps/pom.xml
Labels: testing

#416 CIF-1629 - Enrich PLP / PDP automatically with metadata
  .circleci/ci/it-tests.js
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/page/PageMetadata.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MockExternalizer.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/main/resources/graphql/magento-graphql-category.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
Labels: feature
