Repository adobe/aem-core-cif-components, pull requests merged in 2020-04, with the labels that each got.

#245 releng - Update dependencies for next release
  parent/pom.xml
Labels: releng

#241 CIF-1317 - Support Virtual Products
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-virtualproduct-result.json
  react-components/src/components/Checkout/editableForm.js
  react-components/src/components/Checkout/overview.js
  react-components/src/components/Checkout/paymentsForm.js
  react-components/src/components/Minicart/__test__/cartHandlers.test.js
  react-components/src/components/Minicart/cartInitializer.js
  react-components/src/queries/mutation_add_virtual_to_cart.graphql
  react-components/src/queries/query_cart_details.graphql
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/test/components/commerce/product/addToCartGroupedProductsTest.js
  ui.apps/test/components/commerce/product/addToCartTest.js
Labels: To Verify, feature

#251 CIF-1343 - Absolute path for resource type in product teaser edit dialog
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
Labels: bug

#248 CIF-1256 - Better customizable PLP/PDP URL generation
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderConfiguration.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplEmptyTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/MockUrlProviderConfiguration.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  parent/pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
Labels: Verified

#252 CIF-1331 - The React cart component should not create a cart by default
  react-components/src/actions/cart/__test__/actions.test.js
  react-components/src/actions/cart/actions.js
  react-components/src/actions/cart/index.js
  react-components/src/components/Minicart/__test__/cartHandlers.test.js
  react-components/src/components/Minicart/__test__/cartInitializer.test.js
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/cartInitializer.js
  react-components/src/components/Minicart/minicart.js
  react-components/src/components/Minicart/useMinicart.js
  react-components/src/components/MyAccount/myAccount.js
  react-components/src/components/SignIn/useSignin.js
Labels: Verified, bug

#246 CIF-1337 - Support virtual products that are part of grouped products
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/GroupItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/GroupItem.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-groupedproduct-result.json
  react-components/src/actions/cart/__test__/actions.test.js
  react-components/src/actions/cart/actions.js
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/components/Minicart/minicart.js
  react-components/src/components/Minicart/useMinicart.js
  react-components/src/queries/mutation_add_simple_and_virtual_to_cart.graphql
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
  ui.apps/test/components/commerce/product/addToCartGroupedProductsTest.js
  ui.apps/test/components/commerce/product/addToCartTest.js
Labels: Verified, bug

#253 CIF-1324 - Only one side panel should be open at a time
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/PageContext.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/clientlibs/js/navigation.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigation.html
  ui.apps/test/components/commerce/navigation/navigationTest.js
Labels: bug

#223 #198 Feature/add graphql dynamic filters introspection
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationOptionToSearchAggregationOptionConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationToSearchAggregationConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/FilterAttributeMetadataConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/FilterAttributeMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/PagerImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/PagerPageImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchAggregationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchAggregationOptionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/FilterAttributeMetadataCacheImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/GenericProductAttributeFilterInput.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/FilterAttributeMetadata.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/Pager.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/PagerPage.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchAggregation.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchAggregationOption.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchOptions.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchResultsSet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/FilterAttributeMetadataCache.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchFilterService.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/services/SearchResultsService.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationOptionToSearchAggregationOptionConverterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationToSearchAggregationConverterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/converters/FilterAttributeMetadataConverterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/models/PagerImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/FilterAttributeMetadataCacheImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-attributes-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-introspection-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  parent/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/layerednavigation.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html
Labels: To Verify, feature

#257 CIF-1355 - MVP Faceted Search - Styling
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/layerednavigation.html
Labels: To Verify, bug

#256 CIF-1321 - Empty Commerce tab in page properties
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTemplateRenderConditionServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTemplateRenderConditionServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServletTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
Labels: bug
