Repository adobe/aem-core-cif-components, pull requests merged in 2020-03, with the labels that each got.

#219 CIF-1237 - Use generic authoring placeholder of WCM Core Components for all CIF Components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
Labels: To Verify, enhancement

#184 CIF-1202 - Update the CIF Core Components to use configurations from /conf
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServletTest.java
  bundles/core/src/test/resources/context/jcr-conf.json
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
Labels: To Verify, feature

#220 CIF-1313 - Product carousel no longer displays product configured wit…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: To Verify, bug

#222 CIF-1306 - remove CIF Connector dependency
  README.md
  parent/pom.xml
  ui.apps/pom.xml
Labels: bug

#226 CIF-1314 - Product list doesn't display product without small image
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-result.json
Labels: bug

#225 CIF-1309 - remove productcarousel CSS selector and fix CSS
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
Labels: bug

#228 CIF-1319 - add optional title support for featured category component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
Labels: enhancement

#227 CIF-1303 - add optional title support for related products & product carousel
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
Labels: enhancement

#221 CIF-1182 - Use the same property type in components with product DnD
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/MultiFieldDropTargetPostProcessor.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/MultiFieldDropTargetPostProcessorTest.java
  bundles/core/src/test/resources/context/drop-target-post-processor.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_editConfig.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_editConfig.xml
Labels: To Verify, enhancement

#231 CIF-1244 - CIF Core Component fail gracefully
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
Labels: bug

#233 CIF-1315 - JS of CIF Core Components should be loaded via theme clientlib
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/minicart.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/searchbar.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigation.html
Labels: To Verify, enhancement

#236 CIF-1323 - Malformed category id breaks featured categories
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
Labels: bug

#238 CIF-1223 - add cq:icon for all authorable CIF components
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/.content.xml
Labels: To Verify, enhancement

#237 CIF-1316 - Price display and client-side price fetching for grouped pr…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/Price.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/groupedProducts.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/js/productlist.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commons/v1/price.html
  ui.apps/test/components/commerce/product/groupedProductTest.js
  ui.apps/test/components/commerce/product/productTest.js
  ui.apps/test/components/commerce/productlist/productListTest.js
Labels: feature

#239 CIF-1333 - The Minicart shows an incorrect number of items
  react-components/__mocks__/i18nForTests.js
  react-components/package-lock.json
  react-components/src/components/CartTrigger/__test__/__snapshots__/cartTrigger.test.js.snap
  react-components/src/components/CartTrigger/__test__/cartTrigger.test.js
  react-components/src/components/CartTrigger/cartTrigger.js
  react-components/src/components/Minicart/__test__/__snapshots__/footer.test.js.snap
  react-components/src/components/Minicart/__test__/footer.test.js
  react-components/src/components/Minicart/footer.js
  react-components/src/queries/query_cart_details.graphql
Labels: To Verify, bug

#234 CIF-1072 - Support Registered Cart+Checkout
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/App/app.js
  react-components/src/components/AuthBar/authBar.js
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/editableForm.js
  react-components/src/components/Checkout/overview.js
  react-components/src/components/Checkout/paymentProviders/__test__/braintree.test.js
  react-components/src/components/Checkout/receipt.js
  react-components/src/components/Checkout/useOverview.js
  react-components/src/components/Checkout/useReceipt.js
  react-components/src/components/CreateAccount/__test__/createAccount.test.js
  react-components/src/components/CreateAccount/createAccount.js
  react-components/src/components/CreateAccount/useCreateAccount.js
  react-components/src/components/Minicart/__test__/cartContext.test.js
  react-components/src/components/Minicart/__test__/cartHandlers.test.js
  react-components/src/components/Minicart/__test__/cartInitializer.test.js
  react-components/src/components/Minicart/__test__/cartOptions.test.js
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/cartInitializer.js
  react-components/src/components/SignIn/__test__/signIn.test.js
  react-components/src/components/SignIn/signIn.js
  react-components/src/components/SignIn/useSignin.js
  react-components/src/context/UserContext.js
  react-components/src/context/__test__/UserContext.test.js
  react-components/src/queries/mutation_merge_carts.graphql
  react-components/src/queries/query_customer_cart.graphql
  react-components/src/utils/__test__/cartInitializer.test.js
  react-components/src/utils/cartInitializer.js
  react-components/src/utils/hooks.js
Labels: To Verify, feature

#240 CIF-1334 - Set default quantities of grouped products
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/GroupItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/GroupItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/groupedProducts.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html
Labels: To Verify, bug

#244 CIF-1330 - GraphQL endpoint used by client-side code should be configurable
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeviewexporter/StoreViewExporterTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html
  ui.apps/src/main/javascript/react-components/src/index.js
Labels: To Verify, enhancement
