Repository adobe/aem-core-cif-components, pull requests merged in 2021-02, with the labels that each got.

#461 Nested Product/Categories Pages
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServletTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
Labels: Verified, enhancement

#478 CIF-1918 - Query minification fails for /api/graphql endpoint
  react-components/src/utils/__test__/compressQueryFetch.test.js
  react-components/src/utils/compressQueryFetch.js
Labels: Verified, bug

#477 CIF-1849 - Create minimal default styling for product carousel
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/css/productcarousel.css
Labels: enhancement

#482 CIF-1931 - rename CIF XF component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/.content.xml
Labels: To Verify, bug

#485 CIF-1933 - update XF placeholder message
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/experiencefragment.html
Labels: To Verify, bug

#484 CIF-1462 - Increase the coverage of the source code related to the Se…
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: testing

#479 CIF-1783 - Implement ComponentExporter for product carousel component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/CommerceIdentifierImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/CommonsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplEmptyTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/exporter/productcarousel.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
Labels: To Verify, enhancement

#475 releng - Fix rat exclusions
  parent/pom.xml
Labels: releng

#488 releng - Update AEM and AEMaaCS docker image versions
  .circleci/config.yml
Labels: releng

#491 CIF-1955 - Venia ITs fail for productlist
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
Labels: bug

#487 [CIF-486] export useCartState (Cart Context) for external usage
  react-components/src/components/Minicart/index.js
  react-components/src/index.js
Labels: enhancement

#494 Update README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/README.md
Labels: documentation

#495 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/README.md
Labels: documentation

#496 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/README.md
Labels: documentation

#497 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/README.md
Labels: documentation

#498 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
Labels: documentation

#499 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
Labels: documentation

#500 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
Labels: documentation

#501 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
Labels: documentation

#502 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/README.md
Labels: documentation

#503 Updated README.md - Added "AEM as a Cloud Service" to compatibility
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
Labels: documentation
