Repository adobe/aem-core-cif-components, pull requests merged in 2021-05, with the labels that each got.

#548 Issue#541, Addressing a WAVE accessibility tool error given to the productcollection item
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
Labels: To Verify, enhancement

#557 CIF-2047 - Remove default selectionId for cifcategoryfield
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
Labels: bug

#569 CIF-2007 - Use latest release of CIF add-on from artifactory
  .circleci/ci/it-tests.js
  .circleci/settings.xml
Labels: releng

#572 @trivial - exclude "dependencies" PRs from release notes
  .github/release-drafter.yml
Labels: releng

#571 CIF-1950: Implement integration tests for the JSON export feature
  .circleci/ci/it-tests.js
  .circleci/config.yml
  it/content/pom.xml
  it/content/src/main/content/META-INF/vault/filter.xml
  it/content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  it/content/src/main/content/jcr_root/content/core-components-examples/library/commerce/json/exporter/.content.xml
  it/http/pom.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ComponentJSONExporterIT.java
  it/http/src/test/resources/exporter/categorycarousel.json
  it/http/src/test/resources/exporter/featuredcategorylist.json
  it/http/src/test/resources/exporter/productcarousel.json
  it/http/src/test/resources/exporter/productteaser.json
  it/http/src/test/resources/exporter/relatedproducts.json
  it/http/src/test/resources/exporter/teaser.json
  pom.xml
Labels: testing

#556 CIF-2032: url_path support for category pages
  .circleci/config.yml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/resources/exporter/commerce-teaser.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-category.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-products.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: enhancement
