Repository adobe/aem-core-cif-components, pull requests merged in 2021-06, with the labels that each got.

#590 CIF-2135 - Rename component to "Commerce Experience Fragment"
  .circleci/config.yml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/.content.xml
Labels: Verified, bug

#591 trivial - add missing button component to readme
  README.md
Labels: documentation

#582 CIF-2120: Add StorefrontEvents to PDP
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/AbstractCommerceStorefrontContext.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/ProductStorefrontContextImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/CommerceStorefrontContext.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/ProductStorefrontContext.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/resources/storefront-context/result-storefront-context-product-component.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/storefront-events/js/collector.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
Labels: feature

#583 CIF-2118: Add StorefrontContext to productList
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/CategoryStorefrontContext.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/CategoryStorefrontContextImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-category.json
  bundles/core/src/test/resources/storefront-context/result-storefront-context-productlist-component.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/storefront-events/js/collector.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
Labels: feature

#581 CIF-2122 - Add storefront events to UserContext
  react-components/src/components/AuthBar/__test__/authBar.test.js
  react-components/src/components/AuthBar/authBar.js
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/context/UserContext.js
  react-components/src/context/__test__/UserContext.test.js
Labels: feature

#589 CIF-2119: Add storefront events to checkout components
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/__test__/useCart.test.js
  react-components/src/components/Checkout/__test__/useOverview.test.js
  react-components/src/components/Checkout/overview.js
  react-components/src/components/Checkout/useCart.js
  react-components/src/components/Checkout/useOverview.js
  react-components/src/context/UserContext.js
  react-components/src/queries/query_cart_details.graphql.js
  react-components/src/utils/hooks.js
  react-components/src/utils/mocks/mockMagentoStorefrontEvents.js
  react-components/src/utils/mocks/mutationPlaceOrder.js
  react-components/src/utils/test-utils.js
  ui.apps/package-lock.json
Labels: feature

#587 CIF-2123 - Add storefront events to Minicart
  react-components/src/components/Minicart/__test__/cartContext.test.js
  react-components/src/components/Minicart/__test__/useCartOptions.test.js
  react-components/src/components/Minicart/__test__/useMinicart.test.js
  react-components/src/components/Minicart/__test__/useProduct.test.js
  react-components/src/components/Minicart/cartContext.js
  react-components/src/components/Minicart/useCartOptions.js
  react-components/src/components/Minicart/useMinicart.js
  react-components/src/components/Minicart/useProduct.js
  react-components/src/queries/query_cart_details.graphql.js
  react-components/src/utils/__test__/__snapshots__/dataLayerUtils.test.js.snap
  react-components/src/utils/__test__/dataLayerUtils.test.js
  react-components/src/utils/dataLayerUtils.js
Labels: feature

#596 CIF-2097 - Consume the configured custom HTTP headers in MagentoGraphqlClient
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/DeniedHttpHeaders.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  react-components/src/components/App/app.js
  react-components/src/context/ConfigContext.js
  ui.apps/package-lock.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html
  ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
Labels: Verified, enhancement

#593 CIF-1724: Add Magento Storefront Events Collector
  .gitignore
  extensions/product-recs/content/.prettierignore
  extensions/product-recs/content/.prettierrc
  extensions/product-recs/content/package-lock.json
  extensions/product-recs/content/package.json
  extensions/product-recs/content/pom.xml
  extensions/product-recs/content/src/main/content/META-INF/vault/filter.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/clientlibs/storefront-events-collector/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/clientlibs/storefront-events-collector/js.txt
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/clientlibs/storefront-events-collector/js/collector.js
  extensions/product-recs/content/webpack.config.js
  extensions/product-recs/pom.xml
  pom.xml
Labels: feature
