Repository adobe/aem-core-cif-components, pull requests merged in 2021-11, with the labels that each got.

#733 trivial: recreate ui.apps/package-lock.json without reference to artifactory.corp.adobe.com
  ui.apps/package-lock.json
Labels: releng

#731 CIF-2284 - Improve filter and pagination titles for product collection component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/facetselector.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/paginationbar.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/filters.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/pagination.html
Labels: bug

#735 CIF-2367 [Accessibility][Product Teaser] The product image has an insufficient alternative text attribute
  examples/all/pom.xml
  examples/bundle/src/main/resources/graphql/magento-graphql-productteaser.json
Labels: bug, Verified

#736 CIF-2368 - Increase contrast ratio for product teaser title and price
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
Labels: bug, Verified

#739 CIF-2500: Add add-to-wishlist button to PDP and related components
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  extensions/product-recs/react-components/i18n/en.json
  extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.css
  extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.js
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/ProductCard.test.js
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductCard.test.js.snap
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductRecsGallery.test.js.snap
  react-components/i18n/en.json
  react-components/src/components/BundleProductOptions/__test__/__snapshots__/bundleProductOptions.test.js.snap
  react-components/src/components/BundleProductOptions/__test__/bundleProductOptions.test.js
  react-components/src/components/BundleProductOptions/bundleProductOptions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
  ui.apps/test/components/commerce/product/addToCartGroupedProductsTest.js
  ui.apps/test/components/commerce/product/addToCartTest.js
  ui.apps/test/components/commerce/product/addToWishlistTest.js
  ui.apps/test/components/commerce/productteaser/actionsTest.js
Labels: feature

#737 CIF-2195 - Add additional recommendation types
  bundles/core/pom.xml
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/internal/servlets/AllowedRecTypesDataSourceServlet.java
  extensions/product-recs/bundle/src/test/java/com/adobe/cq/commerce/extensions/recommendations/internal/servlets/AllowedRecTypesDataSourceServletTest.java
  extensions/product-recs/bundle/src/test/java/com/adobe/cq/commerce/extensions/recommendations/testing/TestContext.java
  extensions/product-recs/bundle/src/test/resources/context/datasource-content.json
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_design_dialog/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_dialog/.content.xml
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
  parent/pom.xml
Labels: enhancement, Verified

#742 CIF-2212 fix section title and alignment for component library
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/breadcrumb/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/categorycarousel/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/contentfragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/experiencefragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/featuredcategorylist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/navigation/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/manual-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productcarousel/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productteaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/relatedproducts/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/search/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/teaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/experience-fragments/core-components-examples/library/commerce/commerce-experience-fragment/master/.content.xml
Labels: bug, Verified

#728 CIF-1656: Enhance account information
  react-components/src/utils/__test__/authUtils.test.js
  react-components/src/utils/__test__/localStorageUtils.test.js
  react-components/src/utils/authUtils.js
  react-components/src/utils/localStorageUtils.js
  react-components/src/utils/mocks/mockLocalStorage.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/orderhistory/v1/orderhistory/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/orderhistory/v1/orderhistory/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/orderhistory/v1/orderhistory/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/orderhistory/v1/orderhistory/orderhistory.html
Labels: feature

#743 CIF-2455 - Add to cart of Product Teaser component fails for base products
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.js
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/ProductCard.test.js
Labels: bug, Verified

#740 CIF-2544: remove usage of org.apache.sling.settings
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/SpecificPageStrategy.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/testing/TestContext.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  ui.config/src/content/META-INF/vault/filter.xml
  ui.config/src/content/jcr_root/apps/core/cif/config.author/com.adobe.cq.commerce.core.components.internal.services.SpecificPageStrategy.cfg.json
Labels: bug

#744 CIF-2554: add url_path and url_rewrites to the products sitemap generator
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGenerator.java
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: bug

#761 CIF-2240: remove placeholder overlay for non-empty product recs
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/models/common/package-info.java
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/models/productrecommendations/package-info.java
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editorhook/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editorhook/js.txt
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editorhook/js/overlayHandling.js
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
  extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductRecsGallery.js
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/ProductRecsGallery.test.js
  react-components/src/components/Checkout/__test__/__snapshots__/editableForm.test.js.snap
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/PortalPlacer/PortalPlacer.js
  react-components/src/components/PortalPlacer/__test__/__snapshots__/PortalPlacer.test.js.snap
Labels: bug

#762 CIF-2569: initialise currentStyle when creating ProductImpl and ProductListImpl
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/Utils.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/UtilsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/CatalogPageNotFoundFilterTest.java
Labels: bug

#767 CIF-2578: fix createProductPageUrl caching
  react-components/src/utils/__test__/createProductPageUrl.test.js
  react-components/src/utils/createProductPageUrl.js
Labels: bug
