Repository adobe/aem-core-cif-components, pull requests merged in 2021-09, with the labels that each got.

#669 CIF-2334: remove skus from placeholder data
  bundles/core/src/main/resources/productlist-component-placeholder-data.json
Labels: bug, Verified

#677 CIF-2385: fix NPE in ProductListItemImpl#generateId for placeholder data
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImplTest.java
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: bug

#697 CIF-2215 - Breadcrumb error when no dynamic category page is present
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
Labels: bug, Verified

#672 CIF-2310: Update graphql client dependency to 1.7.4
  .circleci/config.yml
  bundles/core/src/test/java/com/adobe/cq/commerce/core/MockHttpClientBuilderFactory.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/button/ButtonImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/CategoriesSitemapGeneratorTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGeneratorTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  parent/pom.xml
Labels: enhancement

#670 CIF-2299: make the storeView optional
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/App/__test__/app.test.js
  react-components/src/components/App/app.js
  react-components/src/context/ConfigContext.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
Labels: bug, Verified

#676 CIF-2345: update dependencies to meet the ones of peregrine
  examples/ui.frontend/package-lock.json
  examples/ui.frontend/package.json
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
  react-components/package-lock.json
  react-components/package.json
Labels: enhancement, dependencies, breaking

#667 CIF-2246: update peer/dev dependencies for react-components
  examples/ui.frontend/.storybook/main.js
  examples/ui.frontend/package-lock.json
  examples/ui.frontend/package.json
  examples/ui.frontend/webpack.common.js
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
  extensions/product-recs/react-components/webpack.config.js
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/ChangePassword/__test__/__snapshots__/changePassword.test.js.snap
  react-components/src/components/ChangePassword/__test__/changePassword.test.js
  react-components/src/components/Checkbox/__test__/__snapshots__/checkbox.test.js.snap
  react-components/src/components/Checkbox/__test__/checkbox.test.js
  react-components/src/components/Minicart/__test__/useCartOptions.test.js
  react-components/src/components/Minicart/__test__/useProduct.test.js
  react-components/src/components/Password/__test__/__snapshots__/password.test.js.snap
  react-components/src/components/Password/__test__/password.test.js
  react-components/webpack.config.js
  ui.apps/package-lock.json
Labels: enhancement

#678 CIF-2328 - Search field reset button not working in AEM archetype
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/js/searchbar.js
Labels: bug

#699 CIF-2400 - Fields not aligned in commerce teaser edit dialog
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/css/teaser.css
Labels: bug, Verified

#700 CIF-2298 - Menu cache flush is not working as expected
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
Labels: bug

#701 CIF-2312 - Respect "include_in_menu" property in navigation component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-navigation-result.json
Labels: enhancement

#703 releng - updated readme after release
  README.md
  VERSIONS.md
Labels: releng
