Repository adobe/aem-core-cif-components, pull requests merged in 2021-04, with the labels that each got.

#530 CIF-2017 - Core Components: URL encoding
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/resources/exporter/commerce-teaser.json
Labels: Verified, enhancement

#535 CIF-2030: Sort categoriesList response
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-list-uid-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-category-list-uid-sort-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: Verified, bug

#537 CIF-1786 - Implement ComponentExporter for related products component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/resources/exporter/productcarousel.json
  bundles/core/src/test/resources/exporter/related-products.json
  bundles/core/src/test/resources/exporter/upsell-products.json
Labels: Verified, enhancement

#536 CIF-2024 - CIF Add-On: UID support for "Preview with category" feature
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServletTest.java
Labels: Verified, enhancement

#540 CIF-2014 - Migrate to Azul Zulu JDK
  .circleci/config.yml
Labels: releng

#528 CIF-1974 - Core Components: navigation - use UID for category queries
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-navigation-result.json
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-categories-list.json
Labels: enhancement

#538 CIF-2022: Fix category URL for UID
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
Labels: bug

#534 CIF-1971: XF placeholder - use UID for category queries
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImplTest.java
Labels: enhancement

#544 CIF-1983 - Remove deprecated id fields from customer queries
  react-components/src/components/ChangePassword/__tests_/changePassword.test.js
  react-components/src/queries/mutation_change_password.graphql.js
  react-components/src/queries/mutation_create_customer.graphql.js
  react-components/src/queries/mutation_update_customer_information.graphql.js
  react-components/src/queries/query_get_customer_information.graphql.js
Labels: bug

#545 CIF-2039 - Missing root category field in catalog page properties
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
Labels: bug

#547 CIF Page component custom head template overrides support for HtmlPag…
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
Labels: enhancement

#555 CIF-2049 - implement UID support for button component and use URLProvider for the component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetrieverTest.java
  bundles/core/src/test/resources/context/jcr-content-button.json
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: bug, enhancement
