Repository adobe/aem-core-cif-components, pull requests merged in 2021-12, with the labels that each got.

#764 CIF-2574 - Transformer support for product / category title as commerce link text
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/CategoryUrlParameterRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/CommerceLinksTransformerFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ProductUrlParameterRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/CategoryUrlFormat.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/CommerceLinksTransformerTest.java
  bundles/core/src/test/resources/rewriter/ciflinks.html
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: enhancement

#768 Issues/post release
  README.md
  VERSIONS.md
  ui.apps/package-lock.json
Labels: releng

#765 CIF-2568: identify wish list button by data attribute
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js
  ui.apps/test/components/commerce/product/addToWishlistTest.js
Labels: bug

#766 CIF-2566: Add missing datalayer events
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/package-info.java
  bundles/core/src/test/resources/exporter/commerce-teaser-v2.json
  bundles/core/src/test/resources/exporter/commerce-teaser.json
  it/http/src/test/resources/exporter/teaser.json
  react-components/src/components/App/app.js
  react-components/src/index.js
  react-components/src/utils/__test__/useDataLayerEvents.test.js
  react-components/src/utils/useDataLayerEvents.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
Labels: bug
