Repository adobe/aem-core-cif-components, pull requests merged in 2021-01, with the labels that each got.

#457 CIF-1776 - CIF components library clientlib is broken
  examples/ui.frontend/package-lock.json
  examples/ui.frontend/package.json
  examples/ui.frontend/pom.xml
Labels: Verified, bug

#458 CIF-1512 - Dynamic XF on PDP
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/experiencefragment/CommerceExperienceFragment.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/XFMockQueryResultHandler.java
  bundles/core/src/test/resources/context/jcr-content-experiencefragment.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/experiencefragment.html
Labels: Verified, feature

#462 CIF-1735: DataLayer events bugs
  react-components/package-lock.json
  react-components/package.json
  react-components/src/components/AddressForm/addressForm.js
  react-components/src/components/Checkout/overview.js
  react-components/src/components/Minicart/useProduct.js
  react-components/src/utils/__test__/dataLayerUtils.test.js
  react-components/src/utils/dataLayerUtils.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
Labels: Verified, bug

#463 CIF-1803 - Add Commerce Experience Fragment component to CIF components library
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImplTest.java
  examples/README.md
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/experiencefragment/.content.xml
  examples/ui.content/src/main/content/META-INF/vault/filter.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/experiencefragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/experience-fragments/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/experience-fragments/core-components-examples/library/commerce/commerce-experience-fragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/experience-fragments/core-components-examples/library/commerce/commerce-experience-fragment/master/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/NavigationComponentIT.java
Labels: Verified, documentation

#465 CIF-1815 - Remove redundant builds done in CircleCI integration tests jobs
  .circleci/ci/it-tests.js
  .circleci/config.yml
Labels: testing

#464 CIF-1791 - The CIF components library should have UI / Selenium tests
  .circleci/ci/it-tests.js
  .circleci/config.yml
  .gitignore
  pom.xml
  ui.tests/README.md
  ui.tests/pom.xml
  ui.tests/test-module/.eslintrc.js
  ui.tests/test-module/README.md
  ui.tests/test-module/lib/commons.js
  ui.tests/test-module/lib/config.js
  ui.tests/test-module/lib/wdio.commands.js
  ui.tests/test-module/package-lock.json
  ui.tests/test-module/package.json
  ui.tests/test-module/specs/cif-components-library/product-bundle.js
  ui.tests/test-module/specs/cif-components-library/product-carousel.js
  ui.tests/test-module/specs/cif-components-library/product.js
  ui.tests/test-module/specs/cif-components-library/storybook.js
  ui.tests/test-module/wdio.conf.cloud.js
  ui.tests/test-module/wdio.conf.commons.js
  ui.tests/test-module/wdio.conf.local.js
Labels: testing

#466 CQ-4313547 - aemcomponents.dev shows JS console error
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/page.html
  examples/ui.content/src/main/content/META-INF/vault/filter.xml
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
Labels: To Verify, bug

#460 CIF-1787 - Implement ComponentExporter for CIF teaser component (the …
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/CommerceIdentifierImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/CommerceIdentifier.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/CommerceTeaser.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/CommerceTeaserActionItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/resources/exporter/commerce-teaser.json
Labels: To Verify, enhancement

#467 CIF-1788 - Implement ComponentExporter for featured category list component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/resources/exporter/featuredcategories.json
Labels: To Verify, enhancement

#469 Add user data in dataLayer
  react-components/src/components/AuthBar/__test__/__snapshots__/authBar.test.js.snap
  react-components/src/components/AuthBar/__test__/authBar.test.js
  react-components/src/components/AuthBar/authBar.js
  react-components/src/components/Checkout/__test__/editableForm.test.js
  react-components/src/components/Checkout/__test__/useOverview.test.js
Labels: enhancement

#474 @releng - update graphql client dependency to latest version
  parent/pom.xml
Labels: dependencies

#473 CIF-1829 - CIF Core Header component contains hardcoded Venia strings
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/header/Header.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/header/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html
Labels: bug
