Repository adobe/aem-core-cif-components, pull requests merged in 2021-07, with the labels that each got.

#600 Bugfix: PDP displays a bundled product instead of the requested simple product
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/TestProductRetriever.java
  bundles/core/src/test/resources/graphql/magento-graphql-multiple-products-result.json
Labels: To Verify, bug

#607 CIF-2181 - Category Pages are not correctly displayed
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/item.html
Labels: bug

#609 Fix product recs extension version
  extensions/product-recs/content/pom.xml
  extensions/product-recs/pom.xml
Labels: bug

#613 CIF-2174 - Fix flaky useOverview places order test
  react-components/src/components/Checkout/__test__/useOverview.test.js
Labels: testing

#606 CIF-2143: Create Product Recommendations AEM component
  .circleci/config.yml
  extensions/product-recs/bundle/pom.xml
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/common/PriceRangeImpl.java
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/productrecommendations/ProductRecommendationsImpl.java
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/models/common/PriceRange.java
  extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/models/productrecommendations/ProductRecommendations.java
  extensions/product-recs/bundle/src/test/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/common/PriceRangeImplTest.java
  extensions/product-recs/bundle/src/test/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/productrecommendations/ProductRecommendationsImplTest.java
  extensions/product-recs/bundle/src/test/resources/context/jcr-content.json
  extensions/product-recs/content/pom.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_design_dialog/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_dialog/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editor/.content.xml
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editor/css.txt
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editor/css/dialog.css
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editor/js.txt
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/clientlibs/editor/js/productrecommendations.js
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/productrecommendations.html
  extensions/product-recs/pom.xml
  pom.xml
Labels: feature

#608 CIF-2173: Add url resolving for client-side components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlFormat.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/AbstractUrlFormat.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/CategoryPageWithUrlKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/CategoryPageWithUrlPath.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSku.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuAndUrlKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuAndUrlPath.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithUrlKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithUrlPath.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/AbstractCommerceRedirectServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/CategoryPageRedirectServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductPageRedirectServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuAndUrlPathTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/CategoryPageRedirectServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductPageRedirectServletTest.java
  bundles/core/src/test/resources/context/jcr-content-redirect-servlet.json
Labels: feature

#614 CIF-2206 - Fix category_id filters being present on category pages
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
Labels: bug

#618 CIF-2209 - do not enable Sling model caching for MagentoGraphqlClientImpl
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
Labels: bug

#616 CIF-2038 - Migrate to CircleCI contexts
  .circleci/config.yml
  .circleci/settings.xml
Labels: releng

#610 CIF-2182: use v2 for product and product list
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-category-with-staged-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products-collection-with-staged-products.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products-staged.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.less.template
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/product/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/manual-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
Labels: enhancement

#622 CIF-2183 - Do not show pricing information for null values
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/Price.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/clientlibs/js/productcollection.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commons/v1/price.html
  ui.apps/test/components/commerce/product/productTest.js
  ui.apps/test/components/commerce/productcollection/productCollectionTest.js
Labels: To Verify, enhancement

#621 CIF-1923 - Minimal default styling for product component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/css/product.css
Labels: enhancement

#625 CIF-2155 - V2 impl of commerce teaser
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/CommerceTeaser.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/teaser/CommerceTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/exporter/commerce-teaser-v2.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/teaser/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/teaser/.content.xml
  it/content/src/main/content/jcr_root/content/core-components-examples/library/commerce/json/exporter/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceTeaserComponentIT.java
  it/http/src/test/resources/exporter/teaser.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/css/teaser.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/js.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/clientlib/editor/js/teaser.js
Labels: enhancement

#632 CIF-2222: Add config for storefront context render
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/AbstractCommerceStorefrontContext.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/CategoryStorefrontContextImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/ProductStorefrontContextImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchResultsStorefrontContextImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchStorefrontContextImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/datalayer/DataLayerComponentTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchbar/SearchBarImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v2/searchresults/searchresults.html
Labels: enhancement

#598 CIF-1832 Add SitemapGenerator for products and categories
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/CategoriesSitemapGenerator.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGenerator.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/sitemap/SitemapCategoryFilter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/sitemap/SitemapProductFilter.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/CategoriesSitemapGeneratorTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGeneratorTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/testing/Utils.java
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-error.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-2.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-3.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-31.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-32.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-4.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-41.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-42.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-5.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-51.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-category-tree-52.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-product-page-1.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-product-page-2.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-product-page-3.json
  bundles/core/src/test/resources/graphql/sitemap/magento-graphql-sitemap-product-page-error.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  parent/pom.xml
Labels: feature

#631 CIF-2223 - Productlist item shows placeholder image and image at the same time
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/css/productcollection.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
Labels: bug

#630 CIF-2227 - add missing image alt attribute
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverterTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-productteaser-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
Labels: bug

#633 CIF-2242 - CIF Core Components Library product list UI is broken
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/searchresults/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/SearchResultsComponentIT.java
Labels: bug

#634 releng - Update aem-core-cif-react-components dependency to 2.0.0
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
Labels: releng

#643 CIF-2208: remove category_uid request parameter on product lists
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationOptionToSearchAggregationOptionConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationToSearchAggregationConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: enhancement
