Repository adobe/aem-core-cif-components, pull requests merged in 2021-08, with the labels that each got.

#644 CIF-2210: replaced use of @Inject with injector specific annotations
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/datalayer/DataLayerComponent.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchbar/SearchbarImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/navigation/NavigationImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  parent/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/action.html
Labels: enhancement

#642 CIF-2163: remove the usage of /magento/graphql
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
  dispatcher/README.md
  dispatcher/conf/magento-proxy.conf
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/.content.xml
Labels: enhancement

#649 [DevOps] Enable continuous integration deployment to AEMaaCS
  examples/all/pom.xml
Labels: releng

#637 releng - Republish product recommendations extension npm package
  extensions/product-recs/react-components/package-lock.json
  extensions/product-recs/react-components/package.json
Labels: releng

#651 CIF-2269 - 'Call to action text' property broken in product teaser
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
Labels: bug

#653 CIF-2294: fix content package dependencies
  extensions/product-recs/content/pom.xml
  ui.apps/pom.xml
Labels: enhancement

#647 CIF-2177 - Expose configured product identifiers for components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/productFullDetail.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/action.html
  ui.tests/test-module/specs/cif-components-library/product-carousel.js
  ui.tests/test-module/specs/cif-components-library/product-list.js
  ui.tests/test-module/specs/cif-components-library/product-teaser.js
  ui.tests/test-module/specs/cif-components-library/product.js
Labels: feature

#661 CIF-2305 - fix raw product access for mapped product product list items
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemTest.java
Labels: bug, Verified

#662 CIF-2311 - add support for "brand slug" in page title
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/head.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
Labels: bug, Verified

#666 CIF-2279 - Improve accessibility of carousel components
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/carousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/clientlibs/css/carousel.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/css/productcarousel.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/test/components/commerce/carousel/carouselTest.js
Labels: bug

#663 CIF-2254 - Add title attribute to product image links
  extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.js
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductCard.test.js.snap
  extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductRecsGallery.test.js.snap
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html
Labels: enhancement

#656 CIF-2272 - Cannot close category filter accordion once it is open
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/js/productcollection.js
  ui.apps/test/components/commerce/productcollection/productCollectionV2Test.js
Labels: bug

#655 CIF-2291 - Cleanups in searchbar component
  ui.apps/karma.conf.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/css/searchbar.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/js.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/clientlibs/js/searchbar.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v2/searchbar/searchbar.html
  ui.apps/test/components/commerce/searchbar/searchbarTest.js
  ui.apps/webpack.config.js
Labels: enhancement, Verified

#668 CIF-2313: remove use of deprecated api
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlToProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServletTest.java
Labels: bug
