Repository adobe/aem-core-cif-components, pull requests merged in 2021-03, with the labels that each got.

#507 CIF-1962 - Sling model caching introduces issues with PageMetadataImpl
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/datalayer/AssetDataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/head.html
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceTestBase.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java
  it/http/src/test/resources/datalayer/chaz-kangeroo-hoodie-product.json
  it/http/src/test/resources/datalayer/outdoor-productlist-items.json
  it/http/src/test/resources/datalayer/outdoor-productlist.json
Labels: To Verify, bug

#515 CIF-1995 - Update CIF integration tests to Magento 2.4.2 EE
  examples/bundle/pom.xml
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-bundle-product.json
  examples/bundle/src/main/resources/graphql/magento-graphql-grouped-product.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  examples/bundle/src/main/resources/graphql/magento-luma-schema-2.3.5.json
  examples/bundle/src/main/resources/graphql/magento-schema-2.4.2ee.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/ResourceTypeImplementationPicker.java
  examples/bundle/src/test/resources/context/jcr-content.json
Labels: feature, testing

#514 CIF-1920 - Move XFPage dialog extensions to CIF core components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/XFDialogExtensionsRenderConditionServlet.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/XFDialogExtensionsRenderConditionServletTest.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
Labels: feature

#510 CIF-1964 - Show staged flag in product component
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/product/ProductImplTest.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  bundles/core/src/test/resources/graphql/magento-graphql-bundleproduct-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-groupedproduct-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/pom.xml
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-bundle-product.json
  examples/bundle/src/main/resources/graphql/magento-graphql-grouped-product.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  examples/bundle/src/main/resources/graphql/magento-luma-schema-2.3.5.json
  examples/bundle/src/main/resources/graphql/magento-schema-2.4.2ee.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/ResourceTypeImplementationPicker.java
  examples/bundle/src/test/resources/context/jcr-content.json
  parent/pom.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v2/product/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v2/product/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v2/product/title.html
Labels: To Verify, feature

#519 CIF-1965 - Show staged flag in productlist component
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v2/productlist/ProductListImplTest.java
  bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/main/resources/graphql/magento-graphql-category.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products-collection.json
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
  examples/bundle/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/title.html
Labels: feature

#512 CIF-1921 - Minimal default styling for featured category list
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/site/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/site/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/clientlibs/site/css/featuredcategorylist.css
Labels: feature

#517 CIF-1922 - Minimal default styling for product teaser
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/css.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/css/productteaser.css
Labels: enhancement

#521 CIF-1972 - Core Components: product list - use UID for category queries
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderConfiguration.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-category.json
  parent/pom.xml
Labels: Verified, feature

#526 CIF-1984 - Core Components: breadcrumb - use UID for category queries
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-category-breadcrumb-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-breadcrumb-result.json
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-categorylist-breadcrumb.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products-breadcrumb.json
  examples/bundle/src/main/resources/graphql/magento-luma-schema-2.3.5.json
  examples/bundle/src/main/resources/graphql/magento-schema-2.4.2ee.json
Labels: feature
