Repository adobe/aem-core-cif-components, pull requests merged in 2022-08, with the labels that each got.

#943 CIF-2916: add UrlProvider product and category filter hooks
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryPlaceholderRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/CatalogPageNotFoundFilter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/CatalogPageNotFoundFilterTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/exporter/upsell-products.json
  bundles/core/src/test/resources/graphql/magento-graphql-crosssellproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-upsellproducts-result.json
  examples/bundle/pom.xml
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
Labels: enhancement

#945 CIF-2537 - Make Associated Content Service public
  .circleci/ci/it-tests.js
  bundles/core/pom.xml
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/experiencefragments/CommerceExperienceFragmentsRetrieverImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/experiencefragments/CommerceExperienceFragmentsRetrieverTest.java
Labels: enhancement, verified

#946 CIF-2842 - Extend List component to list pages by product or category
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/list/CommerceListImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/list/CommerceListImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/list/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/list/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/sample-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/sample-productlist/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceListComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/NavigationComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/NavigationV1ComponentIT.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/list/v1/list/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/list/v1/list/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/list/v1/list/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/list/v1/list/_cq_dialog/.content.xml
Labels: enhancement, verified

#952 releng - Fix permissions in jest-extension job
  .circleci/config.yml
Labels: releng
