Repository adobe/aem-core-cif-components, pull requests merged in 2022-02, with the labels that each got.

#816 CIF-2650 - Remove unused filter attribute of product picker
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
  ui.apps/test/components/content/teaser/teaserConfigTest.js
Labels: bug

#792 CIF-2235: Support different url formats for different store configurations
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/CategoriesSitemapGenerator.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGenerator.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/SitemapLinkExternalizerProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/AbstractPageUrlFormatsServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/CategoryPageUrlFormatsServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductPageUrlFormatsServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/UrlProvider.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/SitemapLinkExternalizerTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/CategoryPageUrlFormatsServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductPageUrlFormatsServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: Verified, feature

#815 CIF-2560: enable preview filter for product pickers
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
Labels: enhancement

#826 CIF-2695 - readme fixes
  README.md
Labels: documentation

#824 CIF-2690: use environment variable to define cache version
  .circleci/config.yml
Labels: releng

#834 CIF-2680 - Improve Markup of productcollection / productlist component
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/css/productcollection.css
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/arrow-down.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/arrow-up.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-down.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-left.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-right.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-up.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/cross.svg
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/filters.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/pagination.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/sort.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/productlist.html
Labels: enhancement

#832 CIF-2707: fix url format selection from ca config
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
Labels: bug

#829 CIF-2672 - Support category filter for product carousel component
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetriever.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetrieverTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-with-category-result.json
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/bundle/src/main/resources/graphql/magento-graphql-productcarousel-category.json
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productcarousel/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductCarouselComponentIT.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/editor/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/editor/js.txt
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/editor/js/product-carousel-editor.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
Labels: enhancement
