Repository adobe/aem-core-cif-components, pull requests merged in 2022-01, with the labels that each got.

#780 CIF-2602: Grouped products added multiple times to Wish List
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js
  ui.apps/test/components/commerce/product/addToWishlistTest.js
Labels: Verified

#781 CIF-2618: make StoreConfigExporter a ConsumerType
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/DeniedHttpHeaders.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/StoreConfigHtmlPageItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImplTest.java
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: enhancement, breaking

#782 CIF-2612 - move product & productlist to seperate pages to work with the not found filter
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/ui.config/src/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.core.components.internal.servlets.CatalogPageNotFoundFilter.cfg.json
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/breadcrumb/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/contentfragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/experiencefragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/manual-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/sample-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/sample-productlist/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ContentFragmentComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java
  it/http/src/test/resources/datalayer/chaz-kangeroo-hoodie-product.json
  it/http/src/test/resources/datalayer/outdoor-productlist-items.json
  it/http/src/test/resources/datalayer/outdoor-productlist.json
  it/http/src/test/resources/exporter/teaser.json
  ui.tests/test-module/specs/cif-components-library/product-bundle.js
  ui.tests/test-module/specs/cif-components-library/product-list.js
  ui.tests/test-module/specs/cif-components-library/product.js
Labels: enhancement

#777 CIF-2612 - cloudManagerTarget config for examples deployment
  all/pom.xml
  examples/all/pom.xml
  examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/breadcrumb/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/contentfragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/experiencefragment/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/manual-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/sample-product/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/sample-productlist/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ContentFragmentComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java
  it/http/src/test/resources/datalayer/chaz-kangeroo-hoodie-product.json
  it/http/src/test/resources/datalayer/outdoor-productlist-items.json
  it/http/src/test/resources/datalayer/outdoor-productlist.json
  it/http/src/test/resources/exporter/teaser.json
  ui.tests/test-module/specs/cif-components-library/product-bundle.js
  ui.tests/test-module/specs/cif-components-library/product-list.js
  ui.tests/test-module/specs/cif-components-library/product.js
Labels: bug

#788 CIF-2603 - Add visual indication for add to wishlist
  react-components/src/talons/Wishlist/__test__/useAddToWishlistEvent.spec.js
  react-components/src/talons/Wishlist/useAddToWishlistEvent.js
Labels: enhancement

#785 CIF-2503: category context aware product urls
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/CategoryUrlParameterRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderConfiguration.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithCategoryAndUrlKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuAndUrlPath.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuCategoryAndUrlKey.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithUrlPath.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/UrlFormatBase.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/ProductUrlFormat.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/urls/UrlProvider.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/CategoryUrlParameterRetrieverTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/MockUrlProviderConfiguration.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/ProductPageWithSkuAndUrlPathTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/urlformats/UrlFormatBaseTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/context/jcr-page-filter.json
  bundles/core/src/test/resources/graphql/magento-graphql-product-breadcrumb-result.json
  bundles/core/src/test/resources/logback-test.xml
  bundles/core/src/test/resources/test-queries/graphql-requests.log
  examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
Labels: enhancement, Verified

#797 CIF-2644 - Update MSE and recommendations to support more page types
  react-components/src/utils/__test__/hooks.test.js
  react-components/src/utils/__test__/usePageEvent.test.js
  react-components/src/utils/hooks.js
Labels: enhancement

#814 releng - Update versions in README
  README.md
  VERSIONS.md
Labels: releng
