Repository adobe/aem-core-cif-components, pull requests merged in 2022-05, with the labels that each got.

#898 releng - Fix jest jobs on CircleCI
  .circleci/config.yml
Labels: releng

#900 CIF-2866 - Alternative category page takes over the whole navigation
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
Labels: bug

#903 CIF-2127 - Enable showLink options for all product and categoryfields
  extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v2/button/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
Labels: enhancement

#901 CIF-2736 - Support custom sort keys in product listing components
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductSortFieldsDataSourceServlet.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/ProductCollection.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchOptions.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/Sorter.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductSortFieldsDataSourceServletTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-products.json
  bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-sortkeys-result.json
  bundles/core/src/test/resources/results/result-datalayer-searchresults-component.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v2/searchresults/README.md
Labels: verified, feature

#904 CIF-2730 - Product Teaser: add option to open CTA in a new Tab
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
  ui.apps/test/components/commerce/productteaser/actionsTest.js
Labels: enhancement, verified

#851 CIF-2731: add link target to v2 Button
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v2/button/_cq_dialog/.content.xml
Labels: enhancement

#905 CIF-2877: fix jacoco report generation
  bundles/core/pom.xml
  examples/bundle/jacoco.exec
Labels: releng

#906 CIF-2727 - Category Carousel: add option to open CTA in a new Tab
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/Utils.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselBase.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
Labels: feature

#910 CIF-2884 - Commerce teaser dialog clientlib regressions
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v3/teaser/clientlib/editor/js/teaser.js
  ui.apps/test/components/content/teaser/teaserConfigTest.js
Labels: bug, verified

#912 CIF-2836: product color options as css classes
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/VariantValueImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v3/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/VariantValue.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v3/product/ProductImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-configurableproduct-result.json
  bundles/core/src/test/resources/graphql/magento-graphql-configurableproduct-uid-result.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/variantselector.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/variantselector.html
Labels: enhancement
