Repository adobe/aem-core-cif-components, pull requests merged in 2022-04, with the labels that each got.

#876 CIF-2792: Always add SKU to product url format params
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-product-result-url-parameters.json
Labels: bug, Verified

#878 CIF-2811: update frontend-maven-plugin
  examples/ui.frontend/pom.xml
  extensions/product-recs/content/pom.xml
  extensions/product-recs/react-components/pom.xml
  parent/pom.xml
  react-components/pom.xml
  ui.apps/pom.xml
Labels: releng

#884 CIF-1696: Migrate add to cart code to new generic addProductsToCart mutation
  README.md
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/VariantImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/VariantValueImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v3/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Variant.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/VariantValue.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v3/product/ProductImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-product-result-uid-variants.json
  bundles/core/src/test/resources/results/result-product-variants-uid.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products-staged.json
  examples/bundle/src/main/resources/graphql/magento-graphql-products.json
  react-components/src/components/BundleProductOptions/__test__/bundleProductOptions.test.js
  react-components/src/components/BundleProductOptions/bundleProductOptions.js
  react-components/src/components/GiftCardOptions/__test__/giftCardOptions.test.js
  react-components/src/components/GiftCardOptions/giftCardOptions.js
  react-components/src/components/GiftCardOptions/useGiftCardOptions.js
  react-components/src/queries/mutation_add_items_to_cart.graphql.js
  react-components/src/talons/Cart/__test__/useAddToCart.test.js
  react-components/src/talons/Cart/__test__/useAddToCartEvent.test.js
  react-components/src/talons/Cart/useAddToCart.js
  react-components/src/talons/Cart/useAddToCartEvent.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/variantSelector.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/productFullDetail.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/quantity.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/variantselector.html
  ui.apps/test/components/commerce/product/variantSelectorTest.js
Labels: enhancement, verified

#897 CIF-1696: decalare product v3 as tech preview
  README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/README.md
Labels: releng

#885 CIF-2757 - Add tracking annotations for product and category filters in page properties
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
Labels: enhancement, verified
