Repository adobe/aem-core-cif-components, pull requests merged in 2022-06, with the labels that each got.

#920 releng - Fallback to legacy peer dependency check
  .circleci/config.yml
Labels: releng

#918 CIF-2887 - Wrong page component in datalayer
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/AbstractPageDelegator.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/AbstractPageDelegatorTest.java
Labels: bug, verified

#921 CIF-2686 - Filter by category in product list component UI
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchAggregationOptionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchAggregationOption.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
  bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-category.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/filters.html
Labels: verified, feature

#923 CIF-2659 - Add version tag to deployed components queries
  .circleci/ci/deploy-queries.js
Labels: releng

#927 CIF-2919: allow to enforce POST requests for customAttributeMetadata query
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/testing/GraphqlQueryMatcher.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/testing/Utils.java
Labels: enhancement

#928 CIF-2903 - Add login token to client-side price fetching
  ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
  ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
Labels: bug, verified
