Repository adobe/aem-core-cif-components, pull requests merged in 2022-03, with the labels that each got.

#828 CIF-2687 - Push queries to reference repo
  .circleci/ci/ci.js
  .circleci/ci/deploy-queries.js
  .circleci/config.yml
  .gitignore
  bundles/core/src/test/resources/test-queries/graphql-requests.log
Labels: releng

#853 CIF-2526 - Add add-to-cart button in all product collections
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/Utils.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselBase.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/ProductCollection.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/package-info.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImplTest.java
  bundles/core/src/test/resources/context/jcr-content.json
  bundles/core/src/test/resources/exporter/productcarousel.json
  bundles/core/src/test/resources/exporter/related-products.json
  bundles/core/src/test/resources/exporter/upsell-products.json
  examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/venia-theme/venia.css
  examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/cloudconfigs/commerce/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productcarousel/.content.xml
  examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/relatedproducts/.content.xml
  it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductCarouselComponentIT.java
  it/http/src/test/java/com/adobe/cq/commerce/it/http/RelatedProductsComponentIT.java
  it/http/src/test/resources/exporter/productcarousel.json
  it/http/src/test/resources/exporter/relatedproducts.json
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/carousel.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/card.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/actions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/actions.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/js/actions.js
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/loadmoreproducts.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/productcollection.html
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_design_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v2/searchresults/README.md
  ui.apps/test/components/commerce/productcarousel/productcarouselTest.js
  ui.apps/test/components/commerce/productcollection/productCollectionV2Test.js
Labels: enhancement, feature

#848 CIF-2463 - Replace referencetab component with extended picker
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
Labels: enhancement

#854 releng - Replace Azul JDK with OpenJDK images
  .circleci/config.yml
Labels: releng

#831 CIF-2474: enable the Commerce Pages on catalog pages
  it/http/src/test/java/com/adobe/cq/commerce/it/http/CatalogPagePropertiesIT.java
  ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
Labels: enhancement

#852 CIF-2085: upgrade to wcm core components 2.18
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/StoreConfigHtmlPageItem.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/button/ButtonImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageImplTest.java
  parent/pom.xml
Labels: enhancement, Verified

#862 CIF-2761: replace model caching
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/product/ProductImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/productlist/ProductListImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
  bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
  bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Labels: bug, Verified
